### ISSUE TITLE
Add save button on the editor page

### ISSUE THREAD

**Issue by jlVidal** [tajpure/hexo-editor#1]
It would be possible to add a save button? Not just the publish? It's really useful for drafts.

Anyway, great tool. I'd love to help in the fixes/new features.

**Comment by tajpure** [comment]
Hi, @jlVidal . I think this feature could be useful too. If you want to help me with this frature, please feel free to pull requests. Thanks for your issues.

**Comment by tajpure** [comment]
This feature has been added.
