### ISSUE TITLE
How to input thumbnail image path when editing the .md files?

### ISSUE THREAD

**Issue by adamleo** [tajpure/hexo-editor#10]
I found out that is it relatively hard for users to add thumbnails to the blog posts, so I changed the editor layout to as below:

![screen shot 2018-01-30 at 3 31 53 pm](https://user-images.githubusercontent.com/9758779/35548317-bbbf397a-05d2-11e8-8b5c-f6d10ad2896f.png)

However, I couldn't figure out which part of the app takes the data and puts it into the .md files.

Would anybody give some advices?

THanks.

**Comment by tajpure** [comment]
When you publish an article, the call stack will be like this:
https://github.com/tajpure/hexo-editor/blob/master/routes/editor.js#L42 
=>> https://github.com/tajpure/hexo-editor/blob/master/models/file-manager.js#L58
=>> https://github.com/tajpure/hexo-editor/blob/master/models/article.js#L38

As shown above, you should add a new field 'thumbnails'  to the Article model.

**Comment by adamleo** [comment]
<img width="814" alt="screen shot 2018-02-02 at 10 25 33 am" src="https://user-images.githubusercontent.com/9758779/35708717-875f75cc-0803-11e8-8ab8-36149c1ef616.png">
<img width="704" alt="screen shot 2018-02-02 at 10 25 40 am" src="https://user-images.githubusercontent.com/9758779/35708718-879105b0-0803-11e8-8315-6a441728a683.png">
<img width="859" alt="screen shot 2018-02-02 at 10 25 45 am" src="https://user-images.githubusercontent.com/9758779/35708719-87c288d8-0803-11e8-8771-449af91d297f.png">


I've added it before posting this issue, but didn't get anything working. What I've done was shown as in those screenshots, and I believe I've modified multiple other files as well.

Do you mind have a look and give some more advices on this?

Thanks a lot!

**Comment by tajpure** [comment]
Could you show your code online, so that I can review it?

**Comment by adamleo** [comment]
Sure thing, here it is: https://github.com/adamleo/blog-editor.

Please have a look, thanks a lot!

**Comment by tajpure** [comment]
The `thumbnail` field has been generated in the source files, did you fix it?

**Comment by adamleo** [comment]
you mean you updated this repo? so i'll just need to do a fresh pull, right?

**Comment by tajpure** [comment]
I have cloned your project to my machine and tested it, I found the 'thumbnail' generated in the .md files.  
<img width="465" alt="demo" src="https://user-images.githubusercontent.com/1475405/35856650-a2ad6ba6-0b71-11e8-90a8-30aecdcd82f8.png">

**Comment by adamleo** [comment]
ahh that was changed by myself manually.
