### ISSUE TITLE
请问能直接上传剪切板里面的图片吗? 比如QQ截图

### ISSUE THREAD

**Issue by badboy-tian** [tajpure/hexo-editor#12]
就像github这种, 直接在这个界面ctrl+v就能粘贴QQ截图的图片

**Comment by tajpure** [comment]
目前还不支持

**Comment by wuwz** [comment]
推荐用Chrome插件, 微博图床
https://chrome.google.com/webstore/detail/fdfdnfpdplfbbnemmmoklbfjbhecpnhf

**Comment by badboy-tian** [comment]
@wuwz 多谢 多谢
