### ISSUE TITLE
请问下生成的文章文件默认生成是中文标题.html?

### ISSUE THREAD

**Issue by badboy-tian** [tajpure/hexo-editor#13]
能自动生成标题的英文.html吗?

**Comment by badboy-tian** [comment]
大佬, 请问下 在哪里改呢 我可以自己去改 麻烦说一下  我现在提交后 生成的网页都是中文...
![image](https://user-images.githubusercontent.com/2835129/37809542-db8cfe5a-2e8a-11e8-8323-6de047e6c781.png)

**Comment by tajpure** [comment]
文章 URL 以第一次发布或暂存的标题为准。可以先将标题设为英文，发布出去后再把标题改成中文。

**Comment by badboy-tian** [comment]
@tajpure 有没有可能调用翻译api, 把中文标题自动翻译成英文呢? @tajpure
