### ISSUE TITLE
Creating a new post while on draft or posts saves it to post even if you press on save to draft.

### ISSUE THREAD

**Issue by kryztoval** [tajpure/hexo-editor#16]
**Expected behaviour:**
Pressing the icon for "Save draft" should save the document in drafts.

**Actual behaviour:**
The file is saved in posts then tries to be moved to drafts.

**Troubleshooting:**
It seems there is a thrown error
`Unhandled rejection Error: ENOENT: no such file or directory, rename './docs/source/_posts/undefined.md' -> './docs/source/_drafts/undefined.md'
`when trying to rename the file from posts to drafts, this makes the file stay in posts.

**Debug info**
Node: v9.11.1

termux-info 
> Updatable packages: All packages up to date
> System information: Linux localhost 4.4.142-perf+ #1 SMP PREEMPT Thu Jul 19 16:01:35 PDT 2018 aarch64 Android
> Termux-packages arch: aarch64
> Android version: 9
> Device manufacturer: Essential Products
> Device model: PH-1

**Comment by tajpure** [comment]
Thanks, fixed via https://github.com/tajpure/hexo-editor/pull/18
