### ISSUE TITLE
Remove Redis cache dependency

### ISSUE THREAD

**Issue by jlVidal** [tajpure/hexo-editor#2]
It would be possible to remove the Redis dependency? I believe the local cache feature would quite easy to develop. using for example Set: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set

Also if possible make it configuration based

**Comment by tajpure** [comment]
I think It's not need to remove Redis, with Redis cache you can edit your posts cross devices. It seems better than just use the browser local storage.
