### ISSUE TITLE
Add support for other files and folders

### ISSUE THREAD

**Issue by jlVidal** [tajpure/hexo-editor#3]
I notice that the editor just enable to edit posts, drafts and trash files.
Sometimes in the hexo websites, the project can have another folders specific to other pages. Or just for organization purpose.

This feature would allow the management of those files in the hexo-editor. For simplification purpose I believe the format of the files inside of the other folders would be the same as drafts/posts.

**Comment by tajpure** [comment]
I will consider to add it later.
