### ISSUE TITLE
Error start script 'node server.js'

### ISSUE THREAD

**Issue by JLKM** [tajpure/hexo-editor#4]
Hexo-editor is just, what I've been waiting for. But waiting is not over yet, as it seems impossible for me to get hexo-editor running. Both on a local machine with Windows/Node 6.3.1 and on a server with Linux/Node 6.1.

It looks like, my windows-installation is closer. An upgrade to Node 6.3.1 plus a change in package.json from
`jade@^1.11.0`
to
`pug@2.0.0-beta4`
made the road for an errorless
>npm install --production

But
>npm start
with Hexo running in another command-prompt still throws this error:

```
Connected to redis:127.0.0.1:6379
Hexo Editor is listening at port:2048.
Hexo init success.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at Object.exports._errnoException (util.js:1012:11)
    at exports._exceptionWithHostPort (util.js:1035:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Jan\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.3.1
npm ERR! npm  v3.8.1
npm ERR! code ELIFECYCLE
npm ERR! hexo-editor@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hexo-editor@1.0.0 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hexo-editor package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hexo-editor
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hexo-editor
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\vscode\hexo\hexo-editor\npm-debug.log
```

I'm not even able to find `events.js` anywhere in the hexo-editor- or hexo-folders.

Any suggestions, how I can get hexo-editor up and running?

**Comment by tajpure** [comment]
You should install [Redis](http://redis.io/download). Because hexo-editor use it as  cache.

**Comment by JLKM** [comment]
That's a major installation, and furthermore I'm not able to test it on my Windows laptop first. So I'll make do with hexo-admin as my editor for the time being. But keep up the good work.
