### ISSUE TITLE
在线编辑时，输入法中的拼音会带入编辑器

### ISSUE THREAD

**Issue by joseph-bing-han** [tajpure/hexo-editor#5]
在线编辑时，使用中文输入法，拼音也会被带入编辑内容中，
例如要输入 “测试中文输入法 ”
页面显示效果为
> ceshi测试zhongwen测试中文shurufa测试中文输入法 

我想应该是自动保存的逻辑监听了keup吧？

**Comment by tajpure** [comment]
嗯，这是个Bug，我会尽快修复。

**Comment by joseph-bing-han** [comment]
ace已经解决这个问题了
[PR](https://github.com/ajaxorg/ace/pull/3116)

**Comment by tajpure** [comment]
非常感谢

**Comment by tajpure** [comment]
最近比较忙，今天才有时间处理，问题已解决。
