### ISSUE TITLE
 0 files generated

### ISSUE THREAD

**Issue by peer2peer** [tajpure/hexo-editor#6]
When I added one new *.md file in the directory: ./docs/source/_posts (configured in _config.yml as the blog's root directory ./docs) and then click on the generate button at the right-top corner of the page, I found there no files generated (via the console at the server - centos). The outputs of Hexo-editor at the server are listed below:

GET /editor/stash?workspace=posts&id=c007e9130ac9fbe19db37143c5174c06 200 5.411 ms - 23
INFO  Start processing
INFO  Files loaded in 23 ms
INFO  0 files generated in 803 μs
GET /generate 304 26.476 ms - -

**Comment by tajpure** [comment]
Please set your real Hexo blog directory as the "base_dir" in the _config.yml, and then the generate button will work.

**Comment by peer2peer** [comment]
What's the real Hexo blog directory?
The .md files such as the 2 sample files are put at ./docs/source/_posts. 
Then what's the real Hexo blog directory? Sorry, it's not clear.

When I click the generate button, one directory created (./docs/public)
but there are no generated files in the public directory.
The console just indicated, 0 files generated.

**Comment by tajpure** [comment]
The real Hexo blog directory is the blog generated by 'hexo init'. If you already have a Hexo blog, you just need to set your Hexo blog directory as the 'base_dir'. Otherwise you should use 'hexo init blog' to generate your blog first and then set the 'base_dir'.

**Comment by peer2peer** [comment]
Got it! Thanks.
